site_name: 'Express 最佳实践'
repo_name: haoranzhao/express-best-practices
repo_url: https://gitlab.6e-group.com/haoranzhao/express-best-practices

theme:
  name: material
  language: zh

nav:
  - Express 最佳实践: README.md
  - 目录结构: directory-structure.md
  - 配置: conf.md
  - 路由: route.md
  - 模型: model.md
  - 模版: template.md
  - 文档: docs.md
  - 中间件: middleware.md

